<script lang="ts">
export let url: string;
export let liveUrl: string;
</script>

<div class="mx-auto flex w-full flex-col pt-16">
  <div class="form-control w-full">
    <!-- svelte-ignore a11y-label-has-associated-control -->
    <label class="label">
      <span class="footer-title label-text">Badge URL</span>
      <span class="badge badge-outline label-text-alt">string</span>
    </label>
    <div class="input input-bordered input-lg h-32 pt-8">
      <p class="break-all">{url}</p>
    </div>
  </div>

  <div class="mockup-window mt-20 mb-16 border bg-base-300 pb-12">
    <img class="mx-auto h-16" src="{liveUrl}" alt="Shields.io badge | Generated by Az-21/badger-knight" />
  </div>
</div>
